### ISSUE TITLE
Tests do not test code

### ISSUE THREAD

**Issue by engnadeau** [jeffmacinnes/mobileGazeMapping#12]
- Currently, `testData/test_mapGaze.py` only runs the example code
- The output isn't validate for correctness
- Tests should validate the functionality of the code with clear, simple test cases

**Comment by jeffmacinnes** [comment]
Hi @nnadeau, thanks for your suggestion on improving the automated tests. I've modified the tests to include the following:

* confirm the existence of all expected output files 
* validate that the mapped gaze values in the output match what the expected values would be for both the world gaze coordinates and the reference image gaze coordinates
* validate that the output videos are properly formatted and have the expected dimensions
