### ISSUE TITLE
Missing DOIs

### ISSUE THREAD

**Issue by engnadeau** [jeffmacinnes/mobileGazeMapping#14]
- [docs/paper/paper.bib](https://github.com/jeffmacinnes/mobileGazeMapping/blob/master/docs/paper/paper.bib) is missing DOIs for certain references
- e.g., http://www.scitepress.org/DigitalLibrary/Link.aspx?doi=10.5220/0001787803310340
- Use cross-ref: https://www.crossref.org/

**Comment by jeffmacinnes** [comment]
I added DOIs to all references except the one for OpenCV. For that one, I follow their recommended bibTex citation at: [https://github.com/opencv/opencv/wiki/CiteOpenCV](https://github.com/opencv/opencv/wiki/CiteOpenCV)
