### ISSUE TITLE
`pytest` isn't listed in `requirements.txt`

### ISSUE THREAD

**Issue by engnadeau** [jeffmacinnes/mobileGazeMapping#8]
- Starting with a clean image 
```bash
docker run -v `pwd`:`pwd` -w `pwd` -it python:3.6 bash
```

- Installed requirements: 
```bash
pip install -r requirements.txt
```

- Tried to run tests: 
```
pytest
```

- Returned: 
```
bash: pytest: command not found
```

- Potential solutions: https://stackoverflow.com/questions/17803829/how-to-customize-a-requirements-txt-for-multiple-environments

**Comment by jeffmacinnes** [comment]
`pytest` added to `requirements.txt` to ensure this error won't come up in the future
